### ISSUE TITLE
Contao 3.5

### ISSUE THREAD

**Issue by AsfalothDE** [Craffft/contao-crosstabs#1]
Hi! I would like to use your extension in Contao 3.5. Unfortunately I can't install it via the composer plugin, because the composer.json limits installation to Contao 3.4. I've installed it manually in the system/modules directory and it worked just fine in Contao 3.5. Would it be possible to adjust your composer.json to include Contao 3.5 compatibility so it can be installed via composer? That would be great.

**Comment by iCodr8** [comment]
Done

**Comment by AsfalothDE** [comment]
Hi! Unfortunately it didn't work for me. :( Tried the installation on a fresh Contao 3.5.12 with the crosstabs version 1.4 and composer said "Your requirements could not be resolved to an installable set of packages." The version 1.4.0 is striked through in the packages overview. Perhaps the compatibility has to be declared with "3.5.*" or something like that?
